/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kursach;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *30.05.15
 * @author AlexBo$$
 */
public class Kursach extends javax.swing.JFrame {
    double square;
    
    double alLux;
    double alRatedPpower;
    double alHeight;
    double alLamp;
    Map<String, Integer > formLamp;
    Map<String, Integer > formPane;
    /**
     * Creates new form Kursach
     */
    public Kursach() {
        super("Program");
        initComponents();
        formLamp();
        formPane();
        jLux5.addActionListener(new ALLux());
        jLux10.addActionListener(new ALLux());
        jLux20.addActionListener(new ALLux());
        jLux30.addActionListener(new ALLux());
        jLux50.addActionListener(new ALLux());
        jLux70.addActionListener(new ALLux());
        jLux100.addActionListener(new ALLux());
        jLux150.addActionListener(new ALLux());
        jLux200.addActionListener(new ALLux());
        jLux300.addActionListener(new ALLux());
        jLux400.addActionListener(new ALLux());
        jLux500.addActionListener(new ALLux());
        jLux600.addActionListener(new ALLux());
        jLux750.addActionListener(new ALLux());
        jLux1000.addActionListener(new ALLux());
        jLux2000.addActionListener(new ALLux());
        jLux3000.addActionListener(new ALLux());
        jLux10000.addActionListener(new ALLux());
       
        jRatedPpower40.addActionListener(new ALRatedPpower());
        jRatedPpower60.addActionListener(new ALRatedPpower());
        jRatedPpower80.addActionListener(new ALRatedPpower());
        jRatedPpower100.addActionListener(new ALRatedPpower());
        jRatedPpower150.addActionListener(new ALRatedPpower());
        jRatedPpower200.addActionListener(new ALRatedPpower());
        
        jHeight2.addActionListener(new ALHeight());
        jHeight3.addActionListener(new ALHeight());
        jHeight5.addActionListener(new ALHeight());
       
        jLampFluorescent.addActionListener(new ALLamp());
        jLampFilament.addActionListener(new ALLamp());
        jLampHalogen.addActionListener(new ALLamp());
        jLampLed.addActionListener(new ALLamp());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jHeight2 = new javax.swing.JRadioButton();
        jHeight3 = new javax.swing.JRadioButton();
        jHeight5 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLux5 = new javax.swing.JRadioButton();
        jLux10 = new javax.swing.JRadioButton();
        jLux20 = new javax.swing.JRadioButton();
        jLux30 = new javax.swing.JRadioButton();
        jLux50 = new javax.swing.JRadioButton();
        jLux70 = new javax.swing.JRadioButton();
        jLux150 = new javax.swing.JRadioButton();
        jLux750 = new javax.swing.JRadioButton();
        jLux100 = new javax.swing.JRadioButton();
        jLux200 = new javax.swing.JRadioButton();
        jLux300 = new javax.swing.JRadioButton();
        jLux400 = new javax.swing.JRadioButton();
        jLux500 = new javax.swing.JRadioButton();
        jLux600 = new javax.swing.JRadioButton();
        jLux1000 = new javax.swing.JRadioButton();
        jLux2000 = new javax.swing.JRadioButton();
        jLux3000 = new javax.swing.JRadioButton();
        jLux10000 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLampFluorescent = new javax.swing.JRadioButton();
        jLampFilament = new javax.swing.JRadioButton();
        jLampHalogen = new javax.swing.JRadioButton();
        jLampLed = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jRatedPpower40 = new javax.swing.JRadioButton();
        jRatedPpower60 = new javax.swing.JRadioButton();
        jRatedPpower80 = new javax.swing.JRadioButton();
        jRatedPpower100 = new javax.swing.JRadioButton();
        jRatedPpower150 = new javax.swing.JRadioButton();
        jRatedPpower200 = new javax.swing.JRadioButton();
        bHistory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextS = new javax.swing.JFormattedTextField();
        jTextP = new javax.swing.JFormattedTextField();
        jTextPyd = new javax.swing.JFormattedTextField();
        jTextN = new javax.swing.JFormattedTextField();
        bDelete = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTable5Number1 = new javax.swing.JRadioButton();
        jTable5Number2 = new javax.swing.JRadioButton();
        jTable6Number1 = new javax.swing.JRadioButton();
        jTable6Number2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        jTable7Number1 = new javax.swing.JRadioButton();
        jTable7Number2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jPanel10 = new javax.swing.JPanel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jFormattedTextField20 = new javax.swing.JFormattedTextField();
        jFormattedTextField21 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Площадь");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Высота"));

        buttonGroup3.add(jHeight2);
        jHeight2.setText("2 - 3");
        jHeight2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHeight2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jHeight3);
        jHeight3.setText("3 - 4");
        jHeight3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHeight3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jHeight5);
        jHeight5.setText("4 - 6");
        jHeight5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHeight5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHeight3)
                    .addComponent(jHeight2)
                    .addComponent(jHeight5))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jHeight2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHeight3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHeight5))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Люкс"));

        buttonGroup1.add(jLux5);
        jLux5.setText("5");
        jLux5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLux5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jLux10);
        jLux10.setText("10");
        jLux10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLux10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jLux20);
        jLux20.setText("20");
        jLux20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLux20ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jLux30);
        jLux30.setText("30");
        jLux30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLux30ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jLux50);
        jLux50.setText("50");
        jLux50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLux50ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jLux70);
        jLux70.setText("70");

        buttonGroup1.add(jLux150);
        jLux150.setText("150");

        buttonGroup1.add(jLux750);
        jLux750.setText("750");

        buttonGroup1.add(jLux100);
        jLux100.setText("100");

        buttonGroup1.add(jLux200);
        jLux200.setText("200");

        buttonGroup1.add(jLux300);
        jLux300.setText("300");

        buttonGroup1.add(jLux400);
        jLux400.setText("400");

        buttonGroup1.add(jLux500);
        jLux500.setText("500");

        buttonGroup1.add(jLux600);
        jLux600.setText("600");

        buttonGroup1.add(jLux1000);
        jLux1000.setText("1000");

        buttonGroup1.add(jLux2000);
        jLux2000.setText("2000");

        buttonGroup1.add(jLux3000);
        jLux3000.setText("3000");

        buttonGroup1.add(jLux10000);
        jLux10000.setText("10000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLux20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLux200)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLux1000))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLux30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLux300)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLux2000))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLux50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLux400)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLux3000))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLux70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLux500)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLux10000))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLux10)
                    .addComponent(jLux5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLux100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLux600))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLux150)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLux750))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLux5)
                    .addComponent(jLux100)
                    .addComponent(jLux600))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLux10)
                    .addComponent(jLux150)
                    .addComponent(jLux750))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLux20)
                    .addComponent(jLux200)
                    .addComponent(jLux1000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLux30)
                    .addComponent(jLux300)
                    .addComponent(jLux2000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLux50)
                    .addComponent(jLux400)
                    .addComponent(jLux3000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLux70)
                    .addComponent(jLux500)
                    .addComponent(jLux10000)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Тип ламп"));

        buttonGroup2.add(jLampFluorescent);
        jLampFluorescent.setText("Люминесцентные");
        jLampFluorescent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLampFluorescentActionPerformed(evt);
            }
        });

        buttonGroup2.add(jLampFilament);
        jLampFilament.setText("Накаливания");
        jLampFilament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLampFilamentActionPerformed(evt);
            }
        });

        buttonGroup2.add(jLampHalogen);
        jLampHalogen.setText("Галогенные");
        jLampHalogen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLampHalogenActionPerformed(evt);
            }
        });

        buttonGroup2.add(jLampLed);
        jLampLed.setText("Светодиодные");
        jLampLed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLampLedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLampFluorescent)
                    .addComponent(jLampFilament)
                    .addComponent(jLampHalogen)
                    .addComponent(jLampLed))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLampFluorescent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLampFilament)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLampHalogen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLampLed))
        );

        jLabel2.setText("м");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Номинальная мощность"));

        buttonGroup4.add(jRatedPpower40);
        jRatedPpower40.setText("40");
        jRatedPpower40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatedPpower40ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRatedPpower60);
        jRatedPpower60.setText("60");
        jRatedPpower60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatedPpower60ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRatedPpower80);
        jRatedPpower80.setText("80");
        jRatedPpower80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatedPpower80ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRatedPpower100);
        jRatedPpower100.setText("100");
        jRatedPpower100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatedPpower100ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRatedPpower150);
        jRatedPpower150.setText("150");
        jRatedPpower150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatedPpower150ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRatedPpower200);
        jRatedPpower200.setText("200");
        jRatedPpower200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatedPpower200ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jRatedPpower60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRatedPpower100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRatedPpower200)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jRatedPpower40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRatedPpower80)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRatedPpower150)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRatedPpower40)
                    .addComponent(jRatedPpower80)
                    .addComponent(jRatedPpower150))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRatedPpower60)
                    .addComponent(jRatedPpower100)
                    .addComponent(jRatedPpower200)))
        );

        bHistory.setText("История");
        bHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistoryActionPerformed(evt);
            }
        });

        jLabel3.setText("Удельная мощность");

        jLabel4.setText("Мощность");

        jLabel5.setText("Количество");

        jTextS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#.00"))));
        jTextS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSActionPerformed(evt);
            }
        });
        jTextS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSKeyTyped(evt);
            }
        });

        jTextP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jTextP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPActionPerformed(evt);
            }
        });

        jTextPyd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jTextPyd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPydActionPerformed(evt);
            }
        });

        jTextN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jTextN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNActionPerformed(evt);
            }
        });

        bDelete.setText("Очистить");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextN, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPyd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(bDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jTextP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPyd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Свет", jDesktopPane1);

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Марка провода"));

        buttonGroup5.add(jTable5Number1);
        jTable5Number1.setText("ЭФ");
        jTable5Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTable5Number1ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jTable5Number2);
        jTable5Number2.setText("1Ф");
        jTable5Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTable5Number2ActionPerformed(evt);
            }
        });

        buttonGroup7.add(jTable6Number1);
        jTable6Number1.setText("Cu");
        jTable6Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTable6Number1ActionPerformed(evt);
            }
        });

        buttonGroup7.add(jTable6Number2);
        jTable6Number2.setText("Al");
        jTable6Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTable6Number2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Удельный проход");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ПВ", "ПУНП", "ВВГ" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "3", "5" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1,5", "2,5", "4", "6", "10", "16", "25", "35", "50", "70", "95", " " }));

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTable5Number1)
                    .addComponent(jTable5Number2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTable6Number2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTable6Number1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTable5Number1)
                            .addComponent(jTable6Number1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTable6Number2)
                            .addComponent(jTable5Number2)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Способ прокладки"));

        buttonGroup6.add(jTable7Number1);
        jTable7Number1.setText("По земле");
        jTable7Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTable7Number1ActionPerformed(evt);
            }
        });

        buttonGroup6.add(jTable7Number2);
        jTable7Number2.setText("По воздуху");

        jLabel7.setText("lдоп");

        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTable7Number1)
                    .addComponent(jTable7Number2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jTable7Number1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTable7Number2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Интерполяция"));

        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jButton1.setText("Ø");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFormattedTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Расчёт питающих линий"));

        jLabel8.setText("Py");

        jLabel9.setText("Pp");

        jLabel10.setText("lp");

        jLabel11.setText("L");

        jLabel12.setText("M");

        jLabel13.setText("dU");

        jLabel14.setText("Kc");

        jLabel15.setText("K");

        jLabel16.setText("Cos(Phi)");

        jFormattedTextField13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField15.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField16.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField16ActionPerformed(evt);
            }
        });

        jFormattedTextField17.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField18.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField18ActionPerformed(evt);
            }
        });

        jFormattedTextField19.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField19ActionPerformed(evt);
            }
        });

        jFormattedTextField20.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jFormattedTextField21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField14)
                            .addComponent(jFormattedTextField13)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField16)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField17)))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jFormattedTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jFormattedTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jFormattedTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Провода", jDesktopPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable6Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTable6Number1ActionPerformed

    }//GEN-LAST:event_jTable6Number1ActionPerformed

    private void jTable7Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTable7Number1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable7Number1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //* TODO add your handling code here:
        
        Map<String, Integer[] > a1 = new HashMap<String, Integer[]>();

        Integer[] b1 = {3, 5};
        a1.put("ПВ", b1);
        
        Integer[] b2 = {1};
        a1.put("ПУНП", b2);
        
        Integer[] b3 = {1};
        a1.put("ВВГ", b3);
        
        Map<String, Double[] > a2 = new HashMap<String, Double[]>();
        
        Double[] b11 = {1.5, 2.5, 4.0, 6.0, 10.0, 16.0, 25.0, 35.0, 50.0, 70.0, 95.0};
        a2.put("ПВ", b11);
        
        Double[] b22 = {1.5, 2.5, 4.0};
        a2.put("ПУНП", b22);
        
        a2.put("ВВГ", b11);
        
        Double[] res = a2.get("ВВГ");
        for(double r : res){
            System.out.println(r);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSActionPerformed
        // TODO add your handling code here:
        square = Double.parseDouble(jTextS.getText());
        result();
    }//GEN-LAST:event_jTextSActionPerformed

    private void bHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistoryActionPerformed
        JOptionPane.showMessageDialog(null, "ERROR!!!");
    }//GEN-LAST:event_bHistoryActionPerformed

    private void jLux50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLux50ActionPerformed

    }//GEN-LAST:event_jLux50ActionPerformed

    private void jLux30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLux30ActionPerformed

    }//GEN-LAST:event_jLux30ActionPerformed

    private void jLux20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLux20ActionPerformed

    }//GEN-LAST:event_jLux20ActionPerformed

    private void jLux10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLux10ActionPerformed

    }//GEN-LAST:event_jLux10ActionPerformed

    private void jLux5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLux5ActionPerformed

    }//GEN-LAST:event_jLux5ActionPerformed

    private void jHeight5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHeight5ActionPerformed
        formPane();
    }//GEN-LAST:event_jHeight5ActionPerformed

    private void jHeight3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHeight3ActionPerformed
        formPane();
    }//GEN-LAST:event_jHeight3ActionPerformed

    private void jHeight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHeight2ActionPerformed
        formPane();
    }//GEN-LAST:event_jHeight2ActionPerformed

    private void jLampFluorescentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLampFluorescentActionPerformed
        method();
        formLamp();
        jRatedPpower40.setEnabled(false);
        jRatedPpower60.setEnabled(false);
        jRatedPpower100.setEnabled(false);
        jRatedPpower150.setEnabled(false);
        jRatedPpower200.setEnabled(false);
        
        jRatedPpower80.setEnabled(true);
    }//GEN-LAST:event_jLampFluorescentActionPerformed

    
    private void jLampFilamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLampFilamentActionPerformed
        formLamp();
        jRatedPpower40.setEnabled(true);
        jRatedPpower60.setEnabled(true);
        jRatedPpower100.setEnabled(true);
        jRatedPpower150.setEnabled(true);
        jRatedPpower200.setEnabled(true);
        
        jRatedPpower80.setEnabled(false);
    }//GEN-LAST:event_jLampFilamentActionPerformed

    private void jFormattedTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField16ActionPerformed

    private void jFormattedTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField19ActionPerformed

    private void jRatedPpower40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatedPpower40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRatedPpower40ActionPerformed

    private void jRatedPpower80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatedPpower80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRatedPpower80ActionPerformed

    private void jRatedPpower150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatedPpower150ActionPerformed
        
    }//GEN-LAST:event_jRatedPpower150ActionPerformed

    private void jRatedPpower60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatedPpower60ActionPerformed
    
    }//GEN-LAST:event_jRatedPpower60ActionPerformed

    private void jRatedPpower100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatedPpower100ActionPerformed
    
    }//GEN-LAST:event_jRatedPpower100ActionPerformed

    private void jRatedPpower200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatedPpower200ActionPerformed
    
    }//GEN-LAST:event_jRatedPpower200ActionPerformed

    private void jLampHalogenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLampHalogenActionPerformed
        formLamp();
        jRatedPpower40.setEnabled(true);
        jRatedPpower60.setEnabled(true);
        jRatedPpower100.setEnabled(true);
        jRatedPpower150.setEnabled(true);
        jRatedPpower200.setEnabled(true);
        
        jRatedPpower80.setEnabled(true);
    }//GEN-LAST:event_jLampHalogenActionPerformed

    private void jLampLedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLampLedActionPerformed
        formLamp();
        jRatedPpower40.setEnabled(true);
        jRatedPpower60.setEnabled(true);
        jRatedPpower100.setEnabled(true);
        jRatedPpower150.setEnabled(true);
        jRatedPpower200.setEnabled(true);
        
        jRatedPpower80.setEnabled(true);
    }//GEN-LAST:event_jLampLedActionPerformed

    private void jTable6Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTable6Number2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable6Number2ActionPerformed
    /*private void q(){
        String s = jTextS.getText();
        String p = jTextP.getText();
        String pyd = jTextPyd.getText();
        String n = jTextN.getText();   
        
        double A = Double.parseDouble(p);
        double B = Double.parseDouble(n);
        double q = A + B;        
        
        jTextPyd.setText(Double.toString(q));   
    }*/
    private void jFormattedTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField18ActionPerformed
       
    }//GEN-LAST:event_jFormattedTextField18ActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        jTextS.setText("");
        jTextP.setText("");
        jTextPyd.setText("");
        jTextN.setText("");
        //не работает:
        jLux5.setSelected(false);
        jLux10.setSelected(false);
        jLux20.setSelected(false);
        jLux30.setSelected(false);
        jLux50.setSelected(false);
        jLux70.setSelected(false);
        jLux100.setSelected(false);
        jLux150.setSelected(false);
        jLux200.setSelected(false);
        jLux300.setSelected(false);
        jLux400.setSelected(false);
        jLux500.setSelected(false);
        jLux600.setSelected(false);
        jLux750.setSelected(false);
        jLux1000.setSelected(false);
        jLux2000.setSelected(false);
        jLux3000.setSelected(false);
        jLux10000.setSelected(false);
        jRatedPpower40.setSelected(false);
        jRatedPpower60.setSelected(false);
        jRatedPpower80.setSelected(false);
        jRatedPpower100.setSelected(false);
        jRatedPpower150.setSelected(false);
        jRatedPpower200.setSelected(false);
        jHeight2.setSelected(false);
        jHeight3.setSelected(false);
        jHeight5.setSelected(false);
        jLampFluorescent.setSelected(false);
        jLampFilament.setSelected(false);
        jLampHalogen.setSelected(false);
        jLampLed.setSelected(false);    
    }//GEN-LAST:event_bDeleteActionPerformed

    private void jTextPydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPydActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPydActionPerformed

    private void jTable5Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTable5Number1ActionPerformed
        if(jTable5Number1.isSelected()){
         jFormattedTextField18.setText(Double.toString(0.9));
         jFormattedTextField17.setText(Double.toString(592.361));
         jFormattedTextField19.setText(Double.toString(0.9));
        }
    }//GEN-LAST:event_jTable5Number1ActionPerformed

    private void jTable5Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTable5Number2ActionPerformed
        jFormattedTextField18.setText(Double.toString(1));
         jFormattedTextField17.setText(Double.toString(592.361));
         jFormattedTextField19.setText(Double.toString(0.9));
    }//GEN-LAST:event_jTable5Number2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFormattedTextField5.setText("");
        jFormattedTextField6.setText("");
        jFormattedTextField7.setText("");
        jFormattedTextField8.setText("");
        jFormattedTextField9.setText("");
        jFormattedTextField10.setText("");
        jFormattedTextField11.setText("");
        jFormattedTextField12.setText("");
        jFormattedTextField13.setText("");
        jFormattedTextField14.setText("");
        jFormattedTextField15.setText("");
        jFormattedTextField16.setText("");
        jFormattedTextField17.setText("");
        jFormattedTextField18.setText("");
        jFormattedTextField19.setText("");
        jFormattedTextField20.setText("");
        jFormattedTextField21.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSKeyPressed

    }//GEN-LAST:event_jTextSKeyPressed

    private void jTextSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSKeyTyped

    }//GEN-LAST:event_jTextSKeyTyped

    private void jTextPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPActionPerformed

    }//GEN-LAST:event_jTextPActionPerformed

    private void jTextNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNActionPerformed

    }//GEN-LAST:event_jTextNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kursach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kursach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kursach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kursach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kursach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bHistory;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JRadioButton jHeight2;
    private javax.swing.JRadioButton jHeight3;
    private javax.swing.JRadioButton jHeight5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jLampFilament;
    private javax.swing.JRadioButton jLampFluorescent;
    private javax.swing.JRadioButton jLampHalogen;
    private javax.swing.JRadioButton jLampLed;
    private javax.swing.JRadioButton jLux10;
    private javax.swing.JRadioButton jLux100;
    private javax.swing.JRadioButton jLux1000;
    private javax.swing.JRadioButton jLux10000;
    private javax.swing.JRadioButton jLux150;
    private javax.swing.JRadioButton jLux20;
    private javax.swing.JRadioButton jLux200;
    private javax.swing.JRadioButton jLux2000;
    private javax.swing.JRadioButton jLux30;
    private javax.swing.JRadioButton jLux300;
    private javax.swing.JRadioButton jLux3000;
    private javax.swing.JRadioButton jLux400;
    private javax.swing.JRadioButton jLux5;
    private javax.swing.JRadioButton jLux50;
    private javax.swing.JRadioButton jLux500;
    private javax.swing.JRadioButton jLux600;
    private javax.swing.JRadioButton jLux70;
    private javax.swing.JRadioButton jLux750;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRatedPpower100;
    private javax.swing.JRadioButton jRatedPpower150;
    private javax.swing.JRadioButton jRatedPpower200;
    private javax.swing.JRadioButton jRatedPpower40;
    private javax.swing.JRadioButton jRatedPpower60;
    private javax.swing.JRadioButton jRatedPpower80;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton jTable5Number1;
    private javax.swing.JRadioButton jTable5Number2;
    private javax.swing.JRadioButton jTable6Number1;
    private javax.swing.JRadioButton jTable6Number2;
    private javax.swing.JRadioButton jTable7Number1;
    private javax.swing.JRadioButton jTable7Number2;
    private javax.swing.JFormattedTextField jTextN;
    private javax.swing.JFormattedTextField jTextP;
    private javax.swing.JFormattedTextField jTextPyd;
    private javax.swing.JFormattedTextField jTextS;
    // End of variables declaration//GEN-END:variables

    private void method(){
        //энейбол!!!
        jRatedPpower40.setEnabled(true);
    }
    
    private void formLamp(){
        
        formLamp = new HashMap<String, Integer>();
        formLamp.put("Люминесцентные", 1);
        formLamp.put("Накаливания", 2);
        formLamp.put("Галогенные", 3);
        formLamp.put("Светодиодные", 4);   
    }
    
    private void formPane(){
        formPane = new HashMap<String, Integer>();
        formPane.put("2 - 3", 2);
        formPane.put("3 - 4", 3);
        formPane.put("4 - 6", 5);
    }
    
    public void result(){
        System.out.println(square);        
        System.out.println(alLux);
        System.out.println(alRatedPpower);
        System.out.println(alHeight);
        System.out.println(alLamp);
        
        double rez = alLux + alRatedPpower;
        jTextPyd.setText(Double.toString(rez)); 
    }
    
    private class ALLux implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            JRadioButton btn = (JRadioButton)e.getSource(); 
            alLux = Integer.parseInt(btn.getText());
            result();
            }
    }
    
    private class ALRatedPpower implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            JRadioButton btn = (JRadioButton)e.getSource(); 
            alRatedPpower = Integer.parseInt(btn.getText());
            result();
            }
    }
    
    private class ALHeight implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            JRadioButton btn = (JRadioButton)e.getSource(); 
            alHeight = formPane.get(btn.getText());
            result();
            }
    }
    
    private class ALLamp implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            JRadioButton btn = (JRadioButton)e.getSource(); 
            alLamp = formLamp.get(btn.getText());
            result();
            }
    }
}
